name: GitHub Production Test

on:
  push:
    branches:
      - main

jobs:
  Test-Production:
    runs-on: ubuntu-latest
    name: Deploy-Production
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npm run test
